### ISSUE TITLE
Feature request: Provide binary targeting .NET 4

### ISSUE THREAD

**Issue by schierlm** [WendyH/hdsdump#2]
Could you include in your binary releases a binary targeting .NET 4?

Background: Windows 10 new installations (unlike upgrades) will no longer install the compatibility files needed for .NET 2 and .NET 3 by default. You can install them later via control panel (or when you run a .NET 2 app you are prompted to do so) but I'd rather not:

- Once installed they will receive updates every month/patchday (more download and longer update time)
- There are known issues/interferences when running a .NET 2/3 application while a kernel debugger is present on Windows 10 (which I don't think Microsoft is planning to fix), so I prefer not to have any .NET 2/3 programs on my main development machine

Should be enough to copy the project/solution files, change target framework to .NET 4.x (and optionally output filename) and recompile. (At least it worked fine for me).

If you prefer, I can send you a pull request with the changed project/solution files.

Thanks.

**Comment by WendyH** [comment]
No problem. I update the release.

**Comment by schierlm** [comment]
Thanks for the great and fast service :)
