### ISSUE TITLE
Akamai DRM support

### ISSUE THREAD

**Issue by ghost** [WendyH/hdsdump#3]
Are there plans to add Akamai DRM support, like in the original script, soon? I'm trying to run this on a server where I don't have admin rights and I can't get PHP working because it wants MSVC.

**Comment by WendyH** [comment]
And now start the plans.
Can you give me some links to stream with such Akamai DRM protection?

**Comment by ghost** [comment]
Here is a site which uses Akamai DRM encryption:

http://www.viasat3.hu/viasat-play

I don't know if it's accessible outside Hungary (the streams are), so here is an example:

http://www.viasat3.hu/musorok/tetovalt-sef/videos/tetovalt-sef-2-evad-8-resz

```
php AdobeHDS.php --manifest "http://tpr199196sec-vh.akamaihd.net/z/secure/SPE_-_Central_Europe/525/439/TACHEF00208-Hungary,.,_1300.,_670.,mp4.csmil/manifest.f4m?hdnea=st=1482341855~exp=1482342485~acl=/z/secure/SPE_-_Central_Europe/525/439/TACHEF00208-Hungary*~hmac=e94afc28fcec63ec111920453cb68a1fb3a256d9f31c91ee95bb20307e1af47c&hdcore=3.5.0" --delete --auth "hdntl=exp=1482428287~acl=%2fz%2fsecure%2fSPE_-_Central_Europe%2f525%2f439%2fTACHEF00208-Hungary*~data=hdntl~hmac=abc51f4f6218e08f61073a471b46b225867e034098fd56f959f4cfe060bfa596&als=0,3,NaN,0,0,NaN,0,0,0,30,f,0,1500.29,f,s,SZFSJLPQODYB,3.5.0,30&hdcore=3.5.0" --useragent "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0"
```

**Comment by WendyH** [comment]
In ver 2.0 released.
