### ISSUE TITLE
2.0.1.4 executable and stream redirection

### ISSUE THREAD

**Issue by Vangelis66** [WendyH/hdsdump#4]
Hi @WendyH :smile: 

- OS: Windows Vista SP2 32bit, fully patched
- .NET Framework: 4.6.1 32bit, with all quality and security updates.

With every previously released executable (I still have v2.0.0.0RC on disk, which is no more to be found in this repo), by simply issuing `hdsdump -h > Help.txt` I could generate a local .txt copy of the help file: 
```
D:\PHP Portable\AdobeHDSdownloaders\HDSdump\2.0.0.0RC>hdsdump

                  HDSdump by WendyH v2.0.0.0

Please specify the manifest. (switch '-h' or '--help' for help message)

D:\PHP Portable\AdobeHDSdownloaders\HDSdump\2.0.0.0RC>hdsdump -h > Help.txt

D:\PHP Portable\AdobeHDSdownloaders\HDSdump\2.0.0.0RC>
```
However, with latest executable v2.0.1.4, this is no longer true; "Help" is still printed in the command prompt window rather than redirected to local file: 
```
D:\PHP Portable\AdobeHDSdownloaders\HDSdump\2.0.1.4>hdsdump

                  HDSdump by WendyH v2.0.1.4

Please specify the manifest. (switch '-h' or '--help' for help message)

D:\PHP Portable\AdobeHDSdownloaders\HDSdump\2.0.1.4>hdsdump -h > Help.txt
You can use hdsdump with following switches:

 -h |--help              displays this help
 -l |--debug             out debug output to log file
 -p |--play              dump flv data to stderr for piping to another program
 -st|--showtime          show time remaining
 -op|--osproxy           use system proxy (by OS)
 -fp|--fproxy            force proxy for downloading of fragments
     --postdata          data for the POST method for http request
 -wk|--waitkey           wait pressed any key at the end
 -c |--continue          continue if possible downloading with exists file
 -z |--oldmethod         use the old method to download
     --quiet             no output any messages
 -v |--verbose           show exteneded info while dumping
     --testalt           sets all avaliable media also as alternate
 -a |--auth      <param> authentication string for fragment requests (add '?' wi
th parameter to end manifest url)
 -t |--duration  <param> stop dumping after specified time in the file (hh:mm:ss
)
 -fs|--filesize  <param> limit size of the output file
 -m |--manifest  <param> path or url to manifest file for dumping stream (f4m)
 -b |--urlbase   <param> base url for relative path in manifest
 -od|--outdir    <param> destination folder for output file
 -o |--outfile   <param> filename to use for output file
 -th|--threads   <param> number of threads to download fragments
 -q |--quality   <param> selected quality level (low|medium|high) or exact bitra
te
 -ss|--skip      <param> skip time hh:mm:ss
 -f |--start     <param> start from specified fragment
 -lf|--logfile   <param> file for debug output
 -ua|--useragent <param> user-Agent to use for emulation of browser requests
 -re|--referer   <param> referer in the headers http requests
 -ck|--cookies   <param> cookies in the headers http requests
 -H |--headers   <param> http header
 -un|--username  <param> username to use for access to http server
 -ps|--password  <param> password to use for access to http server
 -px|--proxy     <param> proxy for downloading of manifest (http://proxyAddress:
proxyPort)
 -pu|--proxyuser <param> username for proxy server
 -pp|--proxypass <param> password for proxy server
     --adkey     <param> Akamai DRM session key as hexadecimal string
     --lang      <param> default language for audio if alternate audio is presen
t
     --alt       <param> select alternate audio by language, codec, bitrate, str
eamId or label


D:\PHP Portable\AdobeHDSdownloaders\HDSdump\2.0.1.4>
```
I can still generate a local help file by issuing `hdsdump -h > Help.txt 2>&1` but why that change? 
Is it by design or some sort of an unpredicted bug? 
BTW, many thanks for your on-going efforts :+1:

**Comment by WendyH** [comment]
When output redirected (or exists redirected process), all debug messages writed to stderr. This is made for be able to read debug messages while working with a redirected stream. As example, hdsdump work as a transcoder in a media server (such as Kodi or Wild Media Server).
But... switch -h prints help and exits. And this switch can not be used with processing, therefore I can safely return the output to STDOUT when this switch used (implemented in 2.0.1.5).

**Comment by Vangelis66** [comment]
@WendyH wrote: 

> But... switch -h prints help and exits. And this switch can not be used with processing, therefore I can safely return the output to STDOUT when this switch used (implemented in 2.0.1.5).

 Thank you very much for restoring previous behaviour; additional thanks for fixing formatting of generated help.txt file (i.e. getting rid of empty lines etc; however, IMHO, there's one unneeded empty line still: 
```
HDSdump v2.0.1.5. You can use hdsdump with following switches:


 -h |--help              displays this help
```
). 

 Including version details in the help is another welcome addition, but may I suggest you include a standalone `--version|-V` switch for that? This is common practice with every CLI app I've used, e.g. you could implement: 

`hdsdump -V => HDSdump v2.0.1.5` (printed to stdout)

Thanks again :+1:

**Comment by WendyH** [comment]
@Vangelis66, done.

**Comment by Vangelis66** [comment]
This is excellent, sincere thanks :1st_place_medal:
